---
slug: freesoftware
filename: freesoftware
title: What you can do with FREE Software
subtitle: 
description: A book listing FREE software I have used.
author: Gerald S. Brown
copyright: 2014
uuid: 66860a84-7191-4ebc-adbf-df36d8ac6bf6
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
