---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad.
        * Incredibly awesome content about FREE software that you can use.
    media:
      - ebooks
    price: 1995


authors:
  -
    name: "Gerald S. Brown"
    image: /images/MyPic-cropped.jpg
    contact_email: "freesoftware@gerbreown.net"
    bio:
      |
        Author bio [link](https://www.softcover.io)

marketing_content: ''

contact_email: 'freesoftware@gerbreown.net'
hide_custom_domain_footer: false
